title: Jaeyoung Chung
author: Jaeyoung Chung
description: "Ph.D. student at Seoul National University (CompSec Lab). Kernel & GPU driver security: bug discovery, reliable reproduction, and exploitation."
url: "https://j-jaeyoung.github.io"
baseurl: ""

markdown: kramdown
permalink: /blog/:year/:month/:day/:title/
#ins_logo: "./bits-logo.png"

profile_picture: "/jy.jpg"

tracking_id: #

footer: yes
footer_url: "https://github.com/ankitsultana/researcher"
footer_text: "Theme: Researcher by Ankit Sultana"

sass:
    style: compressed
    sass_dir: _sass

nav:
 - name: "About"
   link: "/"
 - name: "CV"
   link: "/cv.pdf"
 - name: "Blog"
   link: "/blog/"
